        // ==================== 塔罗牌数据 (JSON) ====================
        const tarotDeck = [
            // ===== 大阿卡纳 (Major Arcana) - 22张 =====
            { id: 'major_00', name: '愚者', number: 0, element: '风', suit: '大阿卡纳',
                type: 'major', roman: '0' },
            { id: 'major_01', name: '魔术师', number: 1, element: '风', suit: '大阿卡纳',
                type: 'major', roman: 'I' },
            { id: 'major_02', name: '女祭司', number: 2, element: '水', suit: '大阿卡纳',
                type: 'major', roman: 'II' },
            { id: 'major_03', name: '皇后', number: 3, element: '土', suit: '大阿卡纳',
            type: 'major', roman: 'III' },
            { id: 'major_04', name: '皇帝', number: 4, element: '火', suit: '大阿卡纳',
            type: 'major', roman: 'IV' },
            { id: 'major_05', name: '教皇', number: 5, element: '土', suit: '大阿卡纳',
            type: 'major', roman: 'V' },
            { id: 'major_06', name: '恋人', number: 6, element: '风', suit: '大阿卡纳',
            type: 'major', roman: 'VI' },
            { id: 'major_07', name: '战车', number: 7, element: '水', suit: '大阿卡纳',
            type: 'major', roman: 'VII' },
            { id: 'major_08', name: '力量', number: 8, element: '火', suit: '大阿卡纳',
            type: 'major', roman: 'VIII' },
            { id: 'major_09', name: '隐士', number: 9, element: '土', suit: '大阿卡纳',
            type: 'major', roman: 'IX' },
            { id: 'major_10', name: '命运之轮', number: 10, element: '火', suit: '大阿卡纳',
                type: 'major', roman: 'X' },
            { id: 'major_11', name: '正义', number: 11, element: '风', suit: '大阿卡纳',
                type: 'major', roman: 'XI' },
            { id: 'major_12', name: '倒吊人', number: 12, element: '水', suit: '大阿卡纳',
                type: 'major', roman: 'XII' },
            { id: 'major_13', name: '死神', number: 13, element: '水', suit: '大阿卡纳',
                type: 'major', roman: 'XIII' },
            { id: 'major_14', name: '节制', number: 14, element: '火', suit: '大阿卡纳',
                type: 'major', roman: 'XIV' },
            { id: 'major_15', name: '恶魔', number: 15, element: '土', suit: '大阿卡纳',
                type: 'major', roman: 'XV' },
            { id: 'major_16', name: '塔', number: 16, element: '火', suit: '大阿卡纳',
            type: 'major', roman: 'XVI' },
            { id: 'major_17', name: '星星', number: 17, element: '风', suit: '大阿卡纳',
                type: 'major', roman: 'XVII' },
            { id: 'major_18', name: '月亮', number: 18, element: '水', suit: '大阿卡纳',
                type: 'major', roman: 'XVIII' },
            { id: 'major_19', name: '太阳', number: 19, element: '火', suit: '大阿卡纳',
                type: 'major', roman: 'XIX' },
            { id: 'major_20', name: '审判', number: 20, element: '火', suit: '大阿卡纳',
            type: 'major', roman: 'XX' },
            { id: 'major_21', name: '世界', number: 21, element: '土', suit: '大阿卡纳',
                type: 'major', roman: 'XXI' },

            // ===== 小阿卡纳 - 权杖 (Wands) - 火元素 - 14张 =====
            { id: 'wands_01', name: '权杖一', number: 1, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_02', name: '权杖二', number: 2, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_03', name: '权杖三', number: 3, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_04', name: '权杖四', number: 4, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_05', name: '权杖五', number: 5, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_06', name: '权杖六', number: 6, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_07', name: '权杖七', number: 7, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_08', name: '权杖八', number: 8, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_09', name: '权杖九', number: 9, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_10', name: '权杖十', number: 10, element: '火', suit: '权杖', type: 'minor' },
            { id: 'wands_11', name: '权杖侍从', number: 11, element: '火', suit: '权杖', type: 'minor',
                court: '侍从' },
            { id: 'wands_12', name: '权杖骑士', number: 12, element: '火', suit: '权杖', type: 'minor',
                court: '骑士' },
            { id: 'wands_13', name: '权杖王后', number: 13, element: '火', suit: '权杖', type: 'minor',
                court: '王后' },
            { id: 'wands_14', name: '权杖国王', number: 14, element: '火', suit: '权杖', type: 'minor',
                court: '国王' },

            // ===== 小阿卡纳 - 圣杯 (Cups) - 水元素 - 14张 =====
            { id: 'cups_01', name: '圣杯一', number: 1, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_02', name: '圣杯二', number: 2, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_03', name: '圣杯三', number: 3, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_04', name: '圣杯四', number: 4, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_05', name: '圣杯五', number: 5, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_06', name: '圣杯六', number: 6, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_07', name: '圣杯七', number: 7, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_08', name: '圣杯八', number: 8, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_09', name: '圣杯九', number: 9, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_10', name: '圣杯十', number: 10, element: '水', suit: '圣杯', type: 'minor' },
            { id: 'cups_11', name: '圣杯侍从', number: 11, element: '水', suit: '圣杯', type: 'minor',
                court: '侍从' },
            { id: 'cups_12', name: '圣杯骑士', number: 12, element: '水', suit: '圣杯', type: 'minor',
                court: '骑士' },
            { id: 'cups_13', name: '圣杯王后', number: 13, element: '水', suit: '圣杯', type: 'minor',
                court: '王后' },
            { id: 'cups_14', name: '圣杯国王', number: 14, element: '水', suit: '圣杯', type: 'minor',
                court: '国王' },

            // ===== 小阿卡纳 - 宝剑 (Swords) - 风元素 - 14张 =====
            { id: 'swords_01', name: '宝剑一', number: 1, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_02', name: '宝剑二', number: 2, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_03', name: '宝剑三', number: 3, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_04', name: '宝剑四', number: 4, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_05', name: '宝剑五', number: 5, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_06', name: '宝剑六', number: 6, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_07', name: '宝剑七', number: 7, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_08', name: '宝剑八', number: 8, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_09', name: '宝剑九', number: 9, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_10', name: '宝剑十', number: 10, element: '风', suit: '宝剑', type: 'minor' },
            { id: 'swords_11', name: '宝剑侍从', number: 11, element: '风', suit: '宝剑', type: 'minor',
                court: '侍从' },
            { id: 'swords_12', name: '宝剑骑士', number: 12, element: '风', suit: '宝剑', type: 'minor',
                court: '骑士' },
            { id: 'swords_13', name: '宝剑王后', number: 13, element: '风', suit: '宝剑', type: 'minor',
                court: '王后' },
            { id: 'swords_14', name: '宝剑国王', number: 14, element: '风', suit: '宝剑', type: 'minor',
                court: '国王' },

            // ===== 小阿卡纳 - 星币 (Pentacles) - 土元素 - 14张 =====
            { id: 'pents_01', name: '星币一', number: 1, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_02', name: '星币二', number: 2, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_03', name: '星币三', number: 3, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_04', name: '星币四', number: 4, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_05', name: '星币五', number: 5, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_06', name: '星币六', number: 6, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_07', name: '星币七', number: 7, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_08', name: '星币八', number: 8, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_09', name: '星币九', number: 9, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_10', name: '星币十', number: 10, element: '土', suit: '星币', type: 'minor' },
            { id: 'pents_11', name: '星币侍从', number: 11, element: '土', suit: '星币', type: 'minor',
                court: '侍从' },
            { id: 'pents_12', name: '星币骑士', number: 12, element: '土', suit: '星币', type: 'minor',
                court: '骑士' },
            { id: 'pents_13', name: '星币王后', number: 13, element: '土', suit: '星币', type: 'minor',
                court: '王后' },
            { id: 'pents_14', name: '星币国王', number: 14, element: '土', suit: '星币', type: 'minor',
                court: '国王' },
        ];

// 为每张牌添加图片路径
tarotDeck.forEach(card => {
    card.image = 'images/' + card.id + '.jpg';
});
